package springboot.package1;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@ResponseBody
public class StudentController {

	@RequestMapping("go")
	public String hello() {
		return "Hello we are learning Spring Boot"
				+ "\n All the dependencies automatic generated by \"spring initializr\"";
	}
}
